# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 450)
        self.Atimer = QtWidgets.QLCDNumber(Form)
        self.Atimer.setGeometry(QtCore.QRect(150, 80, 200, 120))
        self.Atimer.setLineWidth(0)
        self.Atimer.setObjectName("Atimer")
        self.Aprogress = QtWidgets.QProgressBar(Form)
        self.Aprogress.setGeometry(QtCore.QRect(130, 310, 240, 30))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        self.Aprogress.setFont(font)
        self.Aprogress.setObjectName("Aprogress")
        self.Acache = QtWidgets.QLCDNumber(Form)
        self.Acache.setGeometry(QtCore.QRect(190, 220, 120, 50))
        self.Acache.setLineWidth(0)
        self.Acache.setObjectName("Acache")
        self.Btimer = QtWidgets.QLCDNumber(Form)
        self.Btimer.setGeometry(QtCore.QRect(500, 80, 200, 120))
        self.Btimer.setLineWidth(0)
        self.Btimer.setProperty("value", 60.0)
        self.Btimer.setProperty("intValue", 60)
        self.Btimer.setObjectName("Btimer")
        self.Bprogress = QtWidgets.QProgressBar(Form)
        self.Bprogress.setGeometry(QtCore.QRect(480, 310, 240, 30))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        self.Bprogress.setFont(font)
        self.Bprogress.setProperty("value", 0)
        self.Bprogress.setObjectName("Bprogress")
        self.Bcache = QtWidgets.QLCDNumber(Form)
        self.Bcache.setGeometry(QtCore.QRect(550, 220, 120, 50))
        self.Bcache.setLineWidth(0)
        self.Bcache.setObjectName("Bcache")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "计时器"))
